\begin{titlepage}
    \thispagestyle{empty}
    \centering

\vspace*{1cm}

    % 顶部 JAKA 图片
    \includegraphics[width=0.3\textwidth]{Logo.png} \\[1cm]

    % 硬件用户手册
    {\bfseries\fontsize{48pt}{56pt}\selectfont 硬件用户手册\par}
    \vspace{1cm}

    % 产品图
    \includegraphics[width=0.7\textwidth]{AL系列机器人.pdf} \\[1cm]

    % 型号名称
    {\bfseries\fontsize{29pt}{35pt}\selectfont JAKA AL系列\par}
    \vspace{0.5cm}

    % 版本信息
    {\large 翻译版本（zh）\par}
    {\large 文档版本：\docversion\par}

    \vspace{\fill}

    % 底部信息（右对齐）
    \begin{flushright}
        \large
        机器人：A5L、A12L\\
        控制柜：CAB V3\\
    \end{flushright}

    \vspace{1cm}
\end{titlepage}
