
\clearpage
\thispagestyle{empty}  % 清除页码

% 将内容推到页面底部
\vspace*{\fill}
\begin{flushleft}
    % 插入二维码图片（假设图片位于 _static 文件夹，编译时会被复制到输出目录）
    \includegraphics[width=0.3\textwidth]{官网二维码.png} \\[1.5em]

    % 小四号文字（12pt）
    {\fontsize{14pt}{16pt}\selectfont
    JAKA Robotics Co., Ltd. \\
    Address: Building 6, No. 646 Jianchuan Road, Minhang District, Shanghai, China \\
    Email: docs-support@jaka.com \\
    Website: www.jaka.com}
\end{flushleft}
\vspace{3cm}  % 底部留白，可根据需要调整
