\begin{titlepage}
    \thispagestyle{empty}
    \centering

\vspace*{1cm}

    % 顶部 JAKA 图片
    \includegraphics[width=0.3\textwidth]{Logo.png} \\[1cm]

    % Manual title
    {\bfseries\fontsize{48pt}{56pt}\selectfont Hardware User Manual\par}
    \vspace{1cm}

    % 产品图
    \includegraphics[width=0.7\textwidth]{AL系列机器人.png} \\[1cm]
    
    % Product series
    {\bfseries\fontsize{29pt}{35pt}\selectfont JAKA AL Series\par}
    \vspace{0.5cm}
    
    % Version information
    {\large Original Instructions (en) \par}
    {\large Document Version: \docversion\par}

    \vspace{\fill}
    
    % 底部信息（右对齐）
    \begin{flushright}
        \large
        Robots: A5L, A12L\\
        Control Cabinet: CAB V3 \\
    \end{flushright}
    
    \vspace{1cm}
\end{titlepage}
